<?php

/**
 * Implements hook_secure_permissions().
 *
 * Adding permissions for Express Crowdfunding.
 */
function crowdfunding_secure_permissions($role) {
  $permissions = array(
    'administrator' => array(
      'administer community funded',
    ),
    'developer' => array(
      'administer community funded',
    ),
    'site_owner' => array(
      'administer community funded',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function crowdfunding_form_community_funded_admin_settings_form_alter(&$form, &$form_state, $form_id) {
  if (module_exists('community_funded')) {
    define('community_funded_data_user', 'community_funded_data_user');
    define('community_funded_domain_match', 'community_funded_domain_match');

    variable_set(community_funded_data_user, 'is4V1TA0437HddVdKg7LpR6ebsJJ0m6klrjelRSOhkeYqAo7Px9BUHEoA+1qxhWrqdMLD/5uOCX2YjgJ0j773PQPConqTDY8OZglcy8l8Kkf5m0R6zIiEhSjw7LWdBn8G3nMB8y6OKtMkMXDPXU8o7pmMdiUEpkHxqiPp7meXXE=');
    variable_set(community_funded_domain_match, 'http://www.colorado.edu');
  }
}
